version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    container_name: relabs-db

  server:
    build: .
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'bundle install && ruby server.rb'

