version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./back/db:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    command: 'postgres -c log_statement=all'
    container_name: relabs-db

  back:
    build: .
    volumes:
      - ./back:/app
      - .env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'bundle install && ruby server.rb'
    container_name: relabs-back

  front:
    build: .
    volumes:
      - ./front:/app
      - .env:/app/.env
    ports:
      - "2000:2000"
    command: bash -c 'bundle install && ruby server.rb'
    container_name: relabs-front
