version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./back/db:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command: 'postgres -c log_statement=all'
    container_name: relabs-db

  back: &back
    image: ruby:latest
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./back:/app
      - bundle_data_back:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'gem install bundler && bundle install && ruby server.rb'
    container_name: relabs-back

  sidekiq:
    <<: *back
    container_name: back-jobs
    ports: []
    command: bash -c 'bundle install && sidekiq -r ./jobs/csv_importer_job.rb'

  redis:
    image: redis

  front:
    build: .
    working_dir: /app
    volumes:
      - ./front:/app
      - bundle_data_front:/usr/local/bundle
    ports:
      - "2000:2000"
    command: bash -c 'gem install bundler && bundle install && ruby server.rb'
    container_name: relabs-front

volumes:
  bundle_data_back:
  bundle_data_front: