version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    command: ['postgres', '-c', 'log_statement=all']
    container_name: relabs-db

  server:
    build: .
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RACK_ENV: development
    command: bash -c 'bundle install && ruby server.rb'
