version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./back/db:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command: 'postgres -c log_statement=all'
    container_name: relabs-db

  back: &back
    image: ruby:latest
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'gem install bundler && bundle install && ruby server.rb'
    container_name: relabs-back

  sidekiq:
    <<: *back
    container_name: back-jobs
    ports: []
    command: bash -c 'bundle install && sidekiq -r ./jobs/csv_import_job.rb'

  redis:
    image: redis

  chrome:
    image: browserless/chrome:1.31-chrome-stable
    ports:
      - '3333:3333'
    volumes:
      - .:/app:cached
    environment:
      PORT: 3333

  front:
    image: ruby:latest
    working_dir: /app
    volumes:
      - ./front:/app
    depends_on:
      - chrome 
    ports:
      - "2000:2000"
    command: bash -c 'gem install bundler && bundle install && ruby server.rb'
    container_name: relabs-front
