CREATE TABLE patients (
  id SERIAL PRIMARY KEY,
  cpf VARCHAR UNIQUE NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  birthdate DATE NOT NULL,
  address VARCHAR NOT NULL,
  city VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctors (
  id SERIAL PRIMARY KEY,
  crm VARCHAR NOT NULL,
  crm_state VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  CONSTRAINT unique_crm_state UNIQUE (crm, crm_state),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exams (
  id SERIAL PRIMARY KEY,
  patient_id INT NOT NULL,
  doctor_id INT NOT NULL,
  result_token VARCHAR UNIQUE NOT NULL,
  result_date VARCHAR,
  CONSTRAINT fk_patient_id FOREIGN KEY (patient_id) REFERENCES patients(id),
  CONSTRAINT fk_doctor_id FOREIGN KEY (doctor_id) REFERENCES doctors(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tests (
  id SERIAL PRIMARY KEY,
  exam_id INT NOT NULL,
  type VARCHAR NOT NULL,
  limits VARCHAR NOT NULL,
  results VARCHAR,
  CONSTRAINT fk_exam_id FOREIGN KEY (exam_id) REFERENCES exams(id)
);

CREATE DATABASE test;

\c test

CREATE TABLE patients (
  id SERIAL PRIMARY KEY,
  cpf VARCHAR UNIQUE NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  birthdate DATE NOT NULL,
  address VARCHAR NOT NULL,
  city VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctors (
  id SERIAL PRIMARY KEY,
  crm VARCHAR NOT NULL,
  crm_state VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  CONSTRAINT unique_crm_state UNIQUE (crm, crm_state),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exams (
  id SERIAL PRIMARY KEY,
  patient_id INT NOT NULL,
  doctor_id INT NOT NULL,
  result_token VARCHAR UNIQUE NOT NULL,
  result_date VARCHAR,
  CONSTRAINT fk_patient_id FOREIGN KEY (patient_id) REFERENCES patients(id),
  CONSTRAINT fk_doctor_id FOREIGN KEY (doctor_id) REFERENCES doctors(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tests (
  id SERIAL PRIMARY KEY,
  exam_id INT NOT NULL,
  type VARCHAR NOT NULL,
  limits VARCHAR NOT NULL,
  results VARCHAR,
  CONSTRAINT fk_exam_id FOREIGN KEY (exam_id) REFERENCES exams(id)
);

\q
